CREATE TABLE customers (
    customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR2(50) NOT NULL,
    last_name VARCHAR2(50) NOT NULL,
    email VARCHAR2(120) NOT NULL UNIQUE,
    phone VARCHAR2(30) NOT NULL,
    date_of_birth DATE NOT NULL,
    street VARCHAR2(120) NOT NULL,
    city VARCHAR2(60) NOT NULL,
    state VARCHAR2(30) NOT NULL,
    postal_code VARCHAR2(15) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE insurance_policies (
    policy_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id NUMBER NOT NULL,
    policy_number VARCHAR2(30) NOT NULL UNIQUE,
    policy_type VARCHAR2(10) NOT NULL,
    coverage_amount NUMBER(12, 2) NOT NULL,
    monthly_payment NUMBER(10, 2) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE,
    status VARCHAR2(15) DEFAULT 'ACTIVE' NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_policy_customer FOREIGN KEY (customer_id) REFERENCES customers(customer_id) ON DELETE CASCADE,
    CONSTRAINT chk_policy_type CHECK (policy_type IN ('HOME', 'CAR', 'LIFE')),
    CONSTRAINT chk_policy_status CHECK (status IN ('ACTIVE', 'EXPIRED', 'CANCELLED', 'PENDING')),
    CONSTRAINT chk_policy_dates CHECK (end_date IS NULL OR end_date >= start_date)
);

CREATE TABLE home_policy_details (
    policy_id NUMBER PRIMARY KEY,
    house_address VARCHAR2(150) NOT NULL,
    house_area NUMBER(10, 2) NOT NULL,
    bedrooms NUMBER(3) NOT NULL,
    bathrooms NUMBER(3) NOT NULL,
    house_price NUMBER(12, 2) NOT NULL,
    CONSTRAINT fk_home_policy FOREIGN KEY (policy_id) REFERENCES insurance_policies(policy_id) ON DELETE CASCADE
);

CREATE TABLE car_policy_details (
    policy_id NUMBER PRIMARY KEY,
    make VARCHAR2(50) NOT NULL,
    model VARCHAR2(50) NOT NULL,
    car_year NUMBER(4) NOT NULL,
    vin VARCHAR2(30) NOT NULL UNIQUE,
    mileage_per_year NUMBER(8) NOT NULL,
    CONSTRAINT fk_car_policy FOREIGN KEY (policy_id) REFERENCES insurance_policies(policy_id) ON DELETE CASCADE
);

CREATE TABLE life_policy_details (
    policy_id NUMBER PRIMARY KEY,
    existing_conditions VARCHAR2(500),
    beneficiary VARCHAR2(120) NOT NULL,
    CONSTRAINT fk_life_policy FOREIGN KEY (policy_id) REFERENCES insurance_policies(policy_id) ON DELETE CASCADE
);

CREATE OR REPLACE VIEW current_customer_policies AS
SELECT
    c.customer_id,
    c.first_name,
    c.last_name,
    p.policy_id,
    p.policy_number,
    p.policy_type,
    p.coverage_amount,
    p.monthly_payment,
    p.start_date,
    p.end_date,
    p.status
FROM customers c
JOIN insurance_policies p ON p.customer_id = c.customer_id
WHERE p.status = 'ACTIVE'
  AND p.start_date <= TRUNC(SYSDATE)
  AND (p.end_date IS NULL OR p.end_date >= TRUNC(SYSDATE));

